# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# MD003 - Header style
MD003:
  style: "atx"

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD012 - Multiple consecutive blank lines
MD012:
  maximum: 2

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# MD024 - Multiple headers with the same content
MD024:
  allow_different_nesting: true

# MD025 - Multiple top level headers in the same document
MD025:
  front_matter_title: "^\\s*title\\s*[:=]"

# MD026 - Trailing punctuation in header
MD026:
  punctuation: ".,;:!?"

# MD033 - Inline HTML
MD033:
  allowed_elements: ["br", "details", "summary", "img", "kbd", "sup", "sub"]

# MD041 - First line in file should be a top level header
MD041: false

# MD046 - Code block style
MD046:
  style: "fenced"

# MD048 - Code fence style
MD048:
  style: "backtick"

# MD050 - Strong style should be consistent
MD050:
  style: "asterisk"

# MD051 - Link fragments should be valid
MD051: true
