---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs

  - repo: https://github.com/bemeurer/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: [ "--indent-size", "2" ]
        files: \.sh$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [ "-x" ]
        files: \.sh$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        files: ^(docker-compose\.ya?ml|compose\.ya?ml)$

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-fix
        args: [ "--dialect=postgres" ]
        files: \.sql$
      - id: sqlfluff-lint
        args: [ "--dialect=postgres" ]
        files: \.sql$
