---
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.patch$
      - id: end-of-file-fixer
        exclude: \.patch$
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"] # Allow custom YAML tags in Kubernetes manifests
      - id: check-json
      - id: check-xml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: check-docstring-first
        files: ^python/.*\.py$
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: \.lock$|\.patch$

  # Shell scripts
  - repo: https://github.com/bemeurer/beautysh
    rev: v6.2.1
    hooks:
      - id: beautysh
        args: ["--indent-size", "2", "--force-function-style", "fnpar"]
        files: \.sh$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: ["-x", "-e", "SC1091"]
        files: \.sh$

  # YAML linting (expanded)
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]

  # SQL formatting and linting
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-fix
        args: ["--dialect=postgres", "--exclude-rules=L003,L016"]
        files: \.sql$
      - id: sqlfluff-lint
        args: ["--dialect=postgres", "--exclude-rules=L003,L016"]
        files: \.sql$

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^python/.*\.py$
        args: ["--line-length=88", "--target-version=py39"]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        files: ^python/.*\.py$
        args: ["--profile", "black", "--line-length=88", "--multi-line=3"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        files: ^python/.*\.py$
        args: ["--max-line-length=88", "--extend-ignore=E203,W503,E501"]
        additional_dependencies:
          [
            flake8-docstrings,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-simplify,
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        files: ^python/.*\.py$
        args:
          [
            "--ignore-missing-imports",
            "--strict-optional",
            "--warn-redundant-casts",
          ]
        additional_dependencies: [types-requests, types-PyYAML]

  # Python security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        files: ^python/.*\.py$
        args: ["-c", ".bandit"]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        args: ["--ignore", "DL3008", "--ignore", "DL3009"]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdownlint.yaml"]

  # JSON formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(json|yaml|yml|md)$
        args: ["--write", "--prose-wrap=always", "--print-width=80"]

  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [optional-scope, chore, docs, feat, fix, perf, refactor, style, test]

  # License headers
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: ^python/.*\.py$
        args:
          - --license-filepath
          - LICENSE_HEADER.txt
          - --comment-style
          - "#"

  - repo: local
    hooks:
      # Kubernetes manifest validation
      - id: kube-score
        name: kube-score
        description:
          Kubernetes object analysis with recommendations for improved
          reliability and security
        entry: kube-score score
        language: system
        files: ^k8s/.*\.ya?ml$
        args:
          ["--ignore-test", "pod-networkpolicy", "--ignore-test", "pod-probes"]
