---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: recipe-db
data:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
