---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-database
  namespace: recipe-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-database
  template:
    metadata:
      labels:
        app: recipe-database
    spec:
      containers:
        - name: recipe-database
          image: recipe-database:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: recipe-database-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-database-secret
                  key: POSTGRES_PASSWORD
            - name: DB_MAINT_USER
              valueFrom:
                configMapKeyRef:
                  name: recipe-database-config
                  key: DB_MAINT_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: recipe-database-config
                  key: POSTGRES_DB
            - name: DB_MAINT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipe-database-secret
                  key: DB_MAINT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: recipe-database-pvc
