---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-service
  namespace: recipe-database
  labels:
    app: postgres-exporter
  annotations:
    kube-score/ignore: service-targets-pod
    # Service targets pods from postgres-exporter deployment which is deployed separately
spec:
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
      name: metrics
  type: ClusterIP
