---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: recipe-database
  labels:
    app: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 10002
            runAsGroup: 10002
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9187
              name: metrics
          env:
            - name: DATA_SOURCE_NAME
              valueFrom:
                secretKeyRef:
                  name: recipe-database-secret
                  key: POSTGRES_EXPORTER_DATA_SOURCE_NAME
            - name: PG_EXPORTER_EXTEND_QUERY_PATH
              value: "/etc/postgres_exporter/queries.yaml"
          volumeMounts:
            - mountPath: /etc/postgres_exporter
              name: postgres-exporter-config
              readOnly: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
              ephemeral-storage: "100Mi"
            limits:
              memory: "64Mi"
              cpu: "100m"
              ephemeral-storage: "200Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 10
            periodSeconds: 15
      volumes:
        - name: postgres-exporter-config
          configMap:
            name: postgres-exporter-config
