---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-database-pvc
  namespace: recipe-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
