---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: recipe-db
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  RECIPE_SCRAPER_PASSWORD: "${RECIPE_SCRAPER_PASSWORD}"
