---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: recipe-database
type: Opaque
stringData:
  DB_MAINT_PASSWORD: "${DB_MAINT_PASSWORD}"
  RECIPE_SCRAPER_PASSWORD: "${RECIPE_SCRAPER_PASSWORD}"
