---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recipe-database-postgres-exporter
  namespace: recipe-database
  labels:
    app: recipe-database
    component: postgres-exporter
spec:
  selector:
    matchLabels:
      app: recipe-database
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - recipe-database
