---
apiVersion: v1
kind: Service
metadata:
  name: recipe-database-service
  namespace: recipe-database
  labels:
    app: recipe-database
  annotations:
    kube-score/ignore: service-targets-pod
    # Ignoring: Service selector matches deployment labels (analyzed separately)
spec:
  selector:
    app: recipe-database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187
  type: ClusterIP
