---
apiVersion: v1
kind: Service
metadata:
  name: recipe-database-service
  namespace: recipe-database
spec:
  selector:
    app: recipe-database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
