blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-username/recipe-database/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📚 Documentation
    url: https://github.com/your-username/recipe-database/tree/main/docs
    about: Check our comprehensive documentation for setup and troubleshooting
  - name: 🔒 Security Issues
    url: https://github.com/your-username/recipe-database/security/policy
    about: Report security vulnerabilities privately (see SECURITY.md)
