name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information to help us understand and evaluate your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description:
        Please check the following before submitting a feature request
      options:
        - label:
            I have searched for existing feature requests that might be similar
          required: true
        - label:
            I have read the project roadmap and this feature is not already
            planned
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation?
      placeholder: |
        As a [user type], I want [feature] so that [benefit/outcome].

        Currently, [describe current limitation or problem]...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        I would like to see...

        This could work by...

        The implementation might involve...
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description:
        Describe any alternative solutions or features you've considered
      placeholder: Have you considered any alternative approaches?

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - Database Schema Enhancement
        - New Database Function/Procedure
        - Monitoring/Observability Feature
        - Performance Improvement
        - Security Enhancement
        - Developer Experience Improvement
        - Documentation Enhancement
        - CI/CD Pipeline Feature
        - New Management Script/Tool
        - API Enhancement
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have, not urgent
        - Medium - Would significantly improve experience
        - High - Important for project success
        - Critical - Blocking current work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple change, minimal impact
        - Medium - Moderate change, some impact on multiple components
        - High - Complex change, significant impact across the system
        - Unknown - Not sure about the complexity
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. User Story 1: As a database administrator, I would use this to...
        2. User Story 2: As a developer, this would help me...
        3. User Story 3: As a system operator, I could...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description:
        What would constitute a successful implementation of this feature?
      placeholder: |
        - [ ] Criterion 1: The feature should...
        - [ ] Criterion 2: Users should be able to...
        - [ ] Criterion 3: The system should...
        - [ ] Criterion 4: Documentation should include...

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints
      placeholder: |
        - Performance requirements: [e.g., must handle X requests/sec]
        - Compatibility requirements: [e.g., must work with PostgreSQL 15+]
        - Security requirements: [e.g., must support role-based access]
        - Monitoring requirements: [e.g., must expose metrics]

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups/Examples
      description:
        Include any mockups, diagrams, code examples, or reference
        implementations
      placeholder: |
        ```sql
        -- Example SQL for new function
        SELECT recipe_manager.new_feature(param1, param2);
        ```

        Or describe API endpoints, configuration examples, etc.

  - type: checkboxes
    id: impact-areas
    attributes:
      label: Impact Areas
      description: Which areas of the project would this feature affect?
      options:
        - label: Database Schema
        - label: Database Functions/Procedures
        - label: Monitoring Configuration
        - label: Kubernetes Manifests
        - label: Python Data Processing
        - label: Shell Scripts
        - label: Documentation
        - label: CI/CD Pipeline
        - label: Security Configuration
        - label: Performance/Scalability

  - type: textarea
    id: migration-considerations
    attributes:
      label: Migration/Backward Compatibility
      description:
        Are there any migration concerns or backward compatibility issues?
      placeholder: |
        - Will this require database migrations?
        - Will this break existing functionality?
        - How should existing users adopt this feature?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful
      placeholder: |
        - Links to relevant documentation or similar implementations
        - Screenshots or diagrams
        - Related issues or discussions

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I would like to work on implementing this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature
        - label: I can provide domain expertise or feedback during development
