-- db/init/users/001_create_POSTGRES_USER-template.sql

DO
$$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = '$POSTGRES_USER'
  ) THEN
    EXECUTE format(
      'CREATE USER %I WITH PASSWORD %L',
      '$POSTGRES_USER',
      '$POSTGRES_PASSWORD'
    );
  END IF;
END
$$;

DO
$$
BEGIN
  EXECUTE format('GRANT ALL PRIVILEGES ON SCHEMA recipe_manager TO %I;', '$POSTGRES_USER');
  EXECUTE format('GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA recipe_manager TO %I;', '$POSTGRES_USER');
  EXECUTE format('GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA recipe_manager TO %I;', '$POSTGRES_USER');
  EXECUTE format('GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA recipe_manager TO %I;', '$POSTGRES_USER');
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA recipe_manager GRANT ALL PRIVILEGES ON TABLES TO %I;', '$POSTGRES_USER');
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA recipe_manager GRANT ALL PRIVILEGES ON SEQUENCES TO %I;', '$POSTGRES_USER');
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA recipe_manager GRANT ALL PRIVILEGES ON FUNCTIONS TO %I;', '$POSTGRES_USER');
END
$$;
