-- db/init/users/002_create_recipe_scraper_user.sql.template

DO
$$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_roles WHERE rolname = '$RECIPE_SCRAPER_USER'
  ) THEN
    EXECUTE format(
      'CREATE USER %I WITH PASSWORD %L',
      '$RECIPE_SCRAPER_USER',
      '$RECIPE_SCRAPER_PASSWORD'
    );
  END IF;
END
$$;

DO
$$
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE recipe_database TO %I;', '$RECIPE_SCRAPER_USER');
  EXECUTE format('GRANT USAGE ON SCHEMA recipe_manager TO %I;', '$RECIPE_SCRAPER_USER');
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA recipe_manager TO %I;', '$RECIPE_SCRAPER_USER');
  EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA recipe_manager TO %I;', '$RECIPE_SCRAPER_USER');
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA recipe_manager GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I;', '$RECIPE_SCRAPER_USER');
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA recipe_manager GRANT USAGE, SELECT ON SEQUENCES TO %I;', '$RECIPE_SCRAPER_USER');
END
$$;
